// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD23zqySGLF5Ne7SOKuDzZGvyGXGhRYnII',
    appId: '1:535735543657:web:6a8974b37dab8156677ff8',
    messagingSenderId: '535735543657',
    projectId: 'projet-l3-417fd',
    authDomain: 'projet-l3-417fd.firebaseapp.com',
    storageBucket: 'projet-l3-417fd.firebasestorage.app',
    measurementId: 'G-E5LVD9HS4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwSmBiyqkQLaii1Pua0n0AsDEpQKwgdEY',
    appId: '1:535735543657:android:a223454dee2a26e6677ff8',
    messagingSenderId: '535735543657',
    projectId: 'projet-l3-417fd',
    storageBucket: 'projet-l3-417fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzg8yBitA1Hxlp6Ivfn20g-RiR6P5rnLQ',
    appId: '1:535735543657:ios:05c0f0a19914a391677ff8',
    messagingSenderId: '535735543657',
    projectId: 'projet-l3-417fd',
    storageBucket: 'projet-l3-417fd.firebasestorage.app',
    androidClientId: '535735543657-6s6gk6aooht5umj49b73bdpoq8o0fo0s.apps.googleusercontent.com',
    iosClientId: '535735543657-oipflhkjf8lhptc4dv2neej6ljvaqeep.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzg8yBitA1Hxlp6Ivfn20g-RiR6P5rnLQ',
    appId: '1:535735543657:ios:05c0f0a19914a391677ff8',
    messagingSenderId: '535735543657',
    projectId: 'projet-l3-417fd',
    storageBucket: 'projet-l3-417fd.firebasestorage.app',
    androidClientId: '535735543657-6s6gk6aooht5umj49b73bdpoq8o0fo0s.apps.googleusercontent.com',
    iosClientId: '535735543657-oipflhkjf8lhptc4dv2neej6ljvaqeep.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD23zqySGLF5Ne7SOKuDzZGvyGXGhRYnII',
    appId: '1:535735543657:web:a5e58d70052364d9677ff8',
    messagingSenderId: '535735543657',
    projectId: 'projet-l3-417fd',
    authDomain: 'projet-l3-417fd.firebaseapp.com',
    storageBucket: 'projet-l3-417fd.firebasestorage.app',
    measurementId: 'G-W4MNQQSNM5',
  );

}